export const SHOW_USER_LIST = "SHOW_USER_LIST";
export const SHOW_COMMENT_LIST = "SHOW_COMMENT_LIST";
export const SHOW_ERRORS = "SHOW_ERRORS";
export const SHOW_SUCCESS = "SHOW_SUCCESS";
export const SHOW_LOADING = "SHOW_LOADING";
export const CLEAR_LOADING = "CLEAR_LOADING";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const SET_LOADING = "SET_LOADING";