export const ITEM_GET_ERRORS = "ITEM_GET_ERRORS";
export const ITEM_GET_SUCCESS = "ITEM_GET_SUCCESS";
export const ITEM_GET_LOADING = "ITEM_GET_LOADING";
export const ITEM_SHOW_SPIN = "ITEM_SHOW_SPIN";
export const ITEM_RESET = "ITEM_RESET";
export const ITEM_CLOSE = "ITEM_CLOSE";
export const GET_SUCCESS = "GET_SUCCESS";
export const GET_LOADING = "GET_LOADING";
export const SUBMIT_LOGIN = "SUBMIT_LOGIN";
export const SUBMIT_REGISTER = "SUBMIT_REGISTER";

export const ITEM_CATEGORY_SELECT = "ITEM_CATEGORY_SELECT";
export const ITEM_LOCATION_SELECT = "ITEM_LOCATION_SELECT";
export const ITEM_ACTION_SELECT = "ITEM_ACTION_SELECT";
export const ITEM_GET_ALLITEMS = "ITEM_GET_AllITEMS";
export const ITEM_CREATE_ITEMS = "ITEM_CREATE_ITEMS";
export const ITEM_SEARCH_ITEMS = "ITEM_SEARCH_ITEMS";

